well-typed/cborg

- Data/Binary/Serialise/CBOR/Class.hs
- binary-serialise-cbor.cabal
- demos/Aeson.hs
- tests/Tests/Serialise.hs
This is WIP.
The tests seem to pass though =)
I was wondering ,what does the  FlatTerms.hs test file do? Do I also add tests for the containers instances there as well?
> Add instances for containers

- Data/Binary/Serialise/CBOR/Class.hs
- tests/Main.hs
- tests/Tests/Serialise.hs
This PR is not ready for merge yet and I submit it for feedback. There's no description of encoding format, not enough tests no benchmarks
This implementation doesn't even try to use CBOR maps and uses positional encoding for all data types. Is this OK?
> Add Generic-derived instances for Serialise

- Data/Binary/Serialise/CBOR/Class.hs
- Data/Binary/Serialise/CBOR/Encoding.hs
- Data/Binary/Serialise/CBOR/Read.hs
- bench/Macro/CBOR.hs
- bench/Macro/DeepSeq.hs
- bench/Macro/MemSize.hs
- bench/Micro.hs
- demos/Aeson.hs
- tests/Tests/CBOR.hs
- tests/Tests/Reference.hs
- tests/Tests/Reference/Implementation.hs
- tests/Tests/Serialise.hs
Trivial patch to disable a warning and remove trailing whitespace.
> Fix a warning in demos/Aeson & trailing whitespace

- Data/Binary/Serialise/CBOR/Write.hs
This rewrites serialization to use `exportIntegerToAddr` as suggested by @dcoutts (code is simpler and it's faster: ~19us vs ~12us).
@dcoutts Let me know if this is what you had in mind - I'm not that familiar with the `ByteString` internals (i.e., I hope I'm not doing something silly here).
> Write: improve Integer serialisation for GMP

- binary-serialise-cbor.cabal
- tests/Tests/Orphanage.hs
- tests/Tests/Serialise.hs
> Compatibility with aeson 1.0 and QuickCheck 2.9

- Data/Binary/Serialise/CBOR/Encoding.hs
- Data/Binary/Serialise/CBOR/Encoding.hs-boot
- Data/Binary/Serialise/CBOR/FlatTerm.hs-boot
Written during http://www.meetup.com/London-Haskell-Hacking/events/231965828/ :-)
cc @dcoutts 
(Edited meetup link which was wrong. ht @nmattia :-))
> add show instance for Encoding

- .travis.yml
This is a regression introduced via #99
> We need a 2nd invocation of prep-llvm.sh inside the unpacked srcdist

- src/Data/Binary/Serialise/CBOR/Class.hs
The encodings given by the CBOR RFC are either inefficient (a
ISO8601 string) or imprecise (offset from the epoch in seconds).
Here we implement the extended time RFC (currently an [Internet Draft](https://tools.ietf.org/html/draft-bormann-cbor-time-tag-00#section-3.3)) which provides a greatly improved encoding.
Currently the draft lacks an assigned tag, so for the time being I've stolen `0x2221feca` (chosen at random via roll of a very large dice). I've started the IANA process for getting a tag assigned while the RFC process takes its course. Unfortunately, eventually updating the library to reflect the assigned tag will be a breaking change.
Benchmark | Before | After
------------|------------|-------
serialise UTCTime | 969.9 μs | 65.88 μs
deserialise UTCTime | 1.316 ms | 112.0 μs
> Improve UTCTime encoding

- binary-serialise-cbor/binary-serialise-cbor.cabal
- binary-serialise-cbor/src/Data/Binary/Serialise/CBOR/Pretty.hs
- binary-serialise-cbor/src/Data/Binary/Serialise/CBOR/Read.hs
- binary-serialise-cbor/src/Data/Binary/Serialise/CBOR/Term.hs
- binary-serialise-cbor/src/Data/Binary/Serialise/CBOR/Write.hs
- cbor-tool/Main.hs
- cborg/src/Codec/CBOR/Read.hs
- serialise/bench/versus/Macro/CBOR.hs
- serialise/tests/Tests/CBOR.hs
This is useful for things like #78.
> Add variant of deserialiseFromBytes returning leftover content

- src/tool/Main.hs
Hi, first-time contributor here!
I would appreciate if anyone can take a look at my pull request, and let me know if it needs improvements.
I had to somewhat duplicate parts of the Read module's API. It might instead be better to add something new to the API for decoding multiple values in a given input ByteString/file. I didn't try this because the trailing ByteString that the `IDecode` type gives is strict, which would defeat the point of streaming after the first top-level cbor value. I thought I shouldn't go there without other comments first.
If anyone wants to test this themselves, [here](https://www.dropbox.com/s/2opquqrlcgw8efd/123.cbor?dl=0) is an example of a multi-value cbor file to use as input.
Closes #78.
Signed-off-by: timds <timds_pub@icloud.com>
> Allow cbor-tool to parse files containing multiple cbor-values (#78)

- cborg/src/Codec/CBOR/Read.hs
This exposes the consumed byte count in addition to the leftovers and parsed value. I found this quite useful.
> Expose deserialiseFromBytesWithSize

- serialise/src/Codec/Serialise.hs
- serialise/src/Codec/Serialise/Tutorial.hs
> fix haddock link: Codec.CBOR.Tutorial -> Codec.Serialise.Tutorial

- cborg/src/Codec/CBOR/Magic.hs
> Remove usage of accursedUnutterablePerformIO from withBsPtr

- serialise/src/Codec/Serialise/Tutorial.hs
Minor things, self-explanatory.
> Some typo fixes in the serialise tutorial.

- cborg/cborg.cabal
- cborg/src/Codec/CBOR/Magic.hs
- cborg/src/Codec/CBOR/Read.hs
- serialise/serialise.cabal
- serialise/tests/Main.hs
- serialise/tests/Tests/Boundary.hs
- serialise/tests/Tests/CBOR.hs
- serialise/tests/Tests/Regress.hs
- serialise/tests/Tests/Regress/Issue160.hs
- serialise/tests/Tests/UTF8.hs
- serialise/tests/Tests/Util.hs
Integer overflow checks and complete the UTF8 validity checking.
Still todo: full boundary/edge test cases that expose this class of problem and will ensure no regressions.
> Decoder checks

- cborg/src/Codec/CBOR/Magic.hs
Make use of the new `GHC.Float.castWord32ToFloat` and `castWord64ToDouble` that are provided in base 4.10 and later. This can replace our home grown versions for suitable versions of base. The new primops should be faster than our fallback implementations.
> Use new GHC primitives `castWord32ToFloat`/`castWord64ToDouble`

- cborg-json/cborg-json.cabal
- cborg/src/Codec/CBOR/Decoding.hs
- cborg/src/Codec/CBOR/Pretty.hs
- cborg/tests/Tests/Reference/Implementation.hs
Pardon an automatically-posted pull request; this is a part of [Operation Vanguard](https://github.com/haskell-vanguard/haskell-vanguard). Note that this does not guarantee that tests and benchmarks are buildable.
> Support GHC 8.8

- .travis.yml
- binary-serialise-cbor/binary-serialise-cbor.cabal
- cabal.project
- cbor-tool/cbor-tool.cabal
- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- serialise/serialise.cabal
There will be warnings in GHC-8.8.1 job.
> Test with GHC-8.8.1 + head.hackage

- serialise/src/Codec/Serialise/Class.hs
> Fix instance Serialise RuntimeRep

- .travis.yml
- cabal.project
- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- cborg/tests/Tests/Reference/Implementation.hs
- cborg/tests/Tests/Reference/TestVectors.hs
- serialise/bench/versus/Macro/Load.hs
- serialise/serialise.cabal
Also:
* Regenerate .travis.yml
* Remove -Wnoncanonical-monadfail-instances option
> Update tests and benchmarks for GHC-8.8

- cborg/src/Codec/CBOR/Pretty.hs
This PR fills in the missing `Tokens` constructors that `pprint` was not previously handling.
> Update `pprint` to handle all `Tokens`

- cborg/cborg.cabal
Builds fine and all tests pass.
> Allow QuickCheck 2.14

- cborg/cborg.cabal
Builds fine and all tests pass.
> Allow base64-bytestring 1.1

- cbor-tool/cbor-tool.cabal
- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- serialise/serialise.cabal
Builds fine and all tests pass here.
> Allow aeson 1.5

- cborg/src/Codec/CBOR/Magic.hs
> Fix for primitive-0.7.1.0

- cborg/src/Codec/CBOR/FlatTerm.hs
> Fix decoding on 32-bit systems

- cbor-tool/cbor-tool.cabal
- cborg-json/cborg-json.cabal
- cborg-json/src/Codec/CBOR/JSON.hs
- cborg/cborg.cabal
- cborg/tests/Tests/Reference.hs
- serialise/serialise.cabal
https://hackage.haskell.org/package/aeson-2.0.1.0/changelog
> Support aeson-2.0

- cborg/src/Codec/CBOR/Magic.hs
@bgamari @georgefst @vmchale Would be great if you could have a look. I tested this locally on my M1 Mac with both 8.10.7 and 9.2.2.
Fixes https://github.com/well-typed/cborg/issues/283, https://github.com/well-typed/cborg/issues/276.
> Compatibility shims for AArch64

- .github/workflows/haskell-ci.yml
- cabal.haskell-ci
- serialise/bench/micro/Micro/PkgAesonTH.hs
- serialise/bench/versus/Macro/PkgAesonTH.hs
> Make the `serialise` benchmarks compile with GHC 9+

- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- serialise/serialise.cabal
Signed-off-by: Finley McIlwaine <finleymcilwaine@gmail.com>
> version bumps

- cborg/src/Codec/CBOR/Magic.hs
Builds fine and all tests pass. Fixes #290
> Fix compatibility with primitive 0.7.4.0

- cbor-tool/cbor-tool.cabal
- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- serialise/serialise.cabal
Builds fine and all tests pass.
> Allow vector 0.13

- .github/workflows/haskell-ci.yml
- binary-serialise-cbor/binary-serialise-cbor.cabal
- cbor-tool/cbor-tool.cabal
- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- serialise/serialise.cabal
Only change required was a bump to upper bounds of base.
> Make it build with ghc-9.10

- .github/workflows/haskell-ci.yml
- binary-serialise-cbor/binary-serialise-cbor.cabal
- binary-serialise-cbor/src/Data/Binary/Serialise/CBOR/Read.hs
- cabal.project
- cbor-tool/cbor-tool.cabal
- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- cborg/src/Codec/CBOR/Decoding.hs
- cborg/src/Codec/CBOR/FlatTerm.hs
- cborg/src/Codec/CBOR/Magic.hs
- serialise/serialise.cabal
Resolve #323. Remove unused dependencies and make conditionally needed dependencies specs more precise.
> Issue 323: Remove unused dependencies
