well-typed/cborg

- Data/Binary/Serialise/CBOR/Class.hs
- Data/Binary/Serialise/CBOR/Decoding.hs
- binary-serialise-cbor.cabal
This avoids thunks accumulating during decoding, on the assumption that we ultimately want the decoded result to be fully evaluated. It's possible that not all the strictness annotations are necessary.
Special treatment is needed for `UTCTime`, because `parseTimeM` isn't sufficiently strict.
> Add more strictness when decoding

- Data/Binary/Serialise/CBOR.hs
- Data/Binary/Serialise/CBOR/Class.hs
- Data/Binary/Serialise/CBOR/Encoding.hs
- Data/Binary/Serialise/CBOR/IO.hs
- Data/Binary/Serialise/CBOR/Write.hs
- binary-serialise-cbor.cabal
This does a few more little clean ups.
- Move some `IO` based routines to a fancy new `.IO` module like all the cool new packages do.
- Styling of the source. I used `stylish-haskell` to make several modules have the imports better aligned, but I haven't done this to every module. In general I think automated styling of this stuff would be nice, though.
- Reformatted the `.cabal` file a little.
- Added some very basic documentation, but the top-level module already looks better.
- Add some whitespace. But also, delete some whitespace too.
> More cleanups

- Data/Binary/Serialise/CBOR/Class.hs
- Data/Binary/Serialise/CBOR/Term.hs
This follows up on my previous PR (#5), applying the same treatment to `decodeTerm`. Also includes a fix for #8.
> Further strictness annotations

- Data/Binary/Serialise/CBOR/FlatTerm.hs
- binary-serialise-cbor.cabal
This makes it possible to use `FlatTerm` (typically for QC properties) in client code. I added a missing case to `fromFlatTerm`, and fixed what looks like an off-by-one error (although I'm not completely sure that this is the right place to fix it).
> Expose FlatTerm module and implement some missing bits

- Data/Binary/Serialise/CBOR/Class.hs
- tests/Tests/Orphanage.hs
- tests/Tests/Serialise.hs
Primitive and Storable vector were missing for some reason
I also exported encoding/decoding function for generic vectors. People do define other vector types so they are useful for defining instances for such vectors.
> Serialise instances for _all_ data types in vector

- Data/Binary/Serialise/CBOR/Class.hs
- tests/Tests/Orphanage.hs
- tests/Tests/Serialise.hs
Here are instance for Proxy (in very unlikely case someone needs it)
I'm not sure Fingerprint is right one. It's some hash which is stored in two 64-bit words for convenience. Encoding it as bytestring makes more sense. What do you think?
> Serialise instances for Proxy and Fingerprint

- binary-serialise-cbor.cabal
- stack.yaml
Allows binary-serialize-cbor to be built against Stackage LTS 7.0.
> Bump Stackage LTS, aeson-pretty constraint.

- demos/Simple.hs
This is a maximally simple example of Data.Binary.Serialise.CBOR  usage to make it easy for people to start from.
> Provide a maximally simple example of serialising

- Data/Binary/Serialise/CBOR.hs
- Data/Binary/Serialise/CBOR/Class.hs
- Data/Binary/Serialise/CBOR/Decoding.hs
- Data/Binary/Serialise/CBOR/FlatTerm.hs
- Data/Binary/Serialise/CBOR/Read.hs
- Data/Binary/Serialise/CBOR/Term.hs
- bench/micro/Micro/CBOR.hs
- bench/micro/SimpleVersus.hs
- bench/versus/Macro/CBOR.hs
- binary-serialise-cbor.cabal
- cabal.project
- tests/Tests/CBOR.hs
- tests/Tests/Serialise.hs
The big win is we add a `liftST` operation that allows running ST actions in the decoder monad. This allows decoding instances to use things like mutable arrays etc. This is important for instances for vectors and other similar types.
> Convert decoder to use ST monad

- README.md
Fix the CONTRIBUTING link in README.md since it moved to .github with commit: ff32ced25ad83981e2c3304b628585e28a3de0cc
> Fix the contributing link in README.md

- tests/Main.hs
- tests/Tests/Serialise.hs
This is to cover the `newtype` case for the generics encoding, to make sure it's always adding the tag.
Also adjust test name to clarify what is is for.
> Add generics encoding test for newtypes

- cabal.project
- cbor-tool/Main.hs
- cborg-json/ChangeLog.md
- cborg-json/LICENSE.txt
- cborg-json/Setup.hs
- cborg-json/cborg-json.cabal
- cborg-json/src/Codec/CBOR/JSON.hs
This factors out the logic used by `cbor-tool` for converting between JSON and CBOR into a reusable library.
> Factor out cborg-json

- serialise/src/Codec/Serialise/Tutorial.hs
This was a glaring inaccuracy in the original tutorial text. Ooops.
> Tutorial: Recommend use of words to represent constructor indices

- cborg/src/Codec/CBOR/Read.hs
`Data.ByteString.Lazy.ByteString` expects the invariant that no chunk is empty.
However, runIDecode was breaking this when producing the remaining
content. Fix this.
> Read: Maintain no-empty-chunks invariant of lazy ByteString

- cborg/src/Codec/CBOR/Read.hs
This makes it cleaner to compare instances of this type or of other
data structures holding a field of this type.
> Make DeserialiseFailure derive Eq

- cborg/src/Codec/CBOR/ByteArray/Internal.hs
- cborg/src/Codec/CBOR/Read.hs
- serialise/tests/Tests/Serialise.hs
Fix for compilation of master on x86_32.
BTW, there is something fishy going on with QuickCheck there: see [test results](https://pastebin.com/NSJ8uJtc).
Apart from invalid time calculations, serialization of CUSeconds fails, but it seems that's a fault of buggy Arbitrary instance, as applying the following patch:
```diff
diff --git a/serialise/tests/Tests/Serialise.hs b/serialise/tests/Tests/Serialise.hs
index 8d75ae7..7ed8ac2 100644
--- a/serialise/tests/Tests/Serialise.hs
+++ b/serialise/tests/Tests/Serialise.hs
@@ -218,7 +218,7 @@ testTree = testGroup "Serialise class"
, mkTest (T :: T CUIntMax)
, mkTest (T :: T CClock)
, mkTest (T :: T CTime)
-      , mkTest (T :: T CUSeconds)
+      , mkTest (T :: T CUSeconds_)
, mkTest (T :: T CSUSeconds)
, mkTest (T :: T CFloat)
, mkTest (T :: T …
```
> Fix compilation on x86_32

- cborg/src/Codec/CBOR/Read.hs
- serialise/tests/Tests/Regress.hs
- serialise/tests/Tests/Regress/Issue162.hs
Cases in which the header or bytes are expected would did not
remember that the integer had to be canonical.
This gist shows a failing example
https://gist.github.com/avieth/444f9994384068f3f5bd42a1a987504c
> correct non-canonical integer decoding

- AUTHORS.txt
The old one should no longer be used.
> Update AUTHORS.txt - Alex Mason email address

- serialise/serialise.cabal
Surely the point of using CBOR is that it can be parsed without needing custom tools (as with `binary`, for example)!
> Correct description in serialise.cabal

- cborg/cborg.cabal
- cborg/src/Codec/CBOR/Decoding.hs
- cborg/src/Codec/CBOR/FlatTerm.hs
- cborg/src/Codec/CBOR/Read.hs
- cborg/tests/Main.hs
- cborg/tests/Tests/ByteOffset.hs
- cborg/tests/Tests/CBOR.hs
- cborg/tests/Tests/Reference/Implementation.hs
Get the current `ByteOffset` in the input byte sequence of the Decoder. The Decoder does not provide any facility to get at the input data directly (since that is tricky with an incremental decoder). The next best is this primitive which can be used to keep track of the offset within the input bytes that makes up the encoded form of a term.
By keeping track of the byte offsets before and after decoding a subterm (a pattern captured by `decodeWithByteSpan`) and if the overall input data is retained then this is enables later retrieving the span of bytes for the subterm.
This includes tests. The main property we test is that if we decode a Term where we track the byte span of the whole term and all sub-terms then the bytes we get do indeed deserialise to the same sub-term, or reserialising …
> Add peekByteOffset primitive

- cborg/cborg.cabal
- cborg/src/Codec/CBOR/Read.hs
- cborg/tests/Main.hs
- cborg/tests/Tests/ByteOffset.hs
- cborg/tests/Tests/CBOR.hs
- cborg/tests/Tests/Canonical.hs
- cborg/tests/Tests/Properties.hs
- cborg/tests/Tests/Reference.hs
- cborg/tests/Tests/Reference/Generators.hs
- cborg/tests/Tests/Reference/Implementation.hs
- cborg/tests/Tests/Term.hs
- cborg/tests/Tests/UnitTests.hs
- serialise/tests/Tests/Orphanage.hs
- serialise/tests/Tests/Serialise.hs
- serialise/tests/Tests/Serialise/Canonical.hs
* Improve the reference implementations representation
* Representations now cover more non-canonical forms
* Improve generator coverage of non-canonical forms
* systematic treatment of non-canonical floating NaNs
* new principled tests based on a commuting diagram
* tests generalised and instantiated for lots of types
This adds tests that catch the bug fixed in #183.
> Major testsuite improvements, including canonical form tests

- cborg/cborg.cabal
- serialise/serialise.cabal
- stack.yaml
Allow cborg to build with GHC 8.6 and lts=13.8
> Bump version to GHC 8.6 and lts-13.8

- cborg/src/Codec/CBOR/Magic.hs
This addresses #193.
If the `OPTIMIZE_GMP` flag is set, then `Data.Bits#unsafeShiftL` is imported.
This is relatively naive in that it just chains off of the `HAVE_BYTESWAP_PRIMOPS` and `MEM_UNALIGNED_OPS` checks, but that seemed preferable to adding an extra `ifdef`.
This was tested on a local project and _seems_ to work as-expected, although I haven't had the chance to thoroughly benchmark anything.
> Adds required imports when OPTIMIZE_GMP is disabled

- cborg-json/ChangeLog.md
- cborg-json/bench/Main.hs
- cborg-json/cborg-json.cabal
- cborg-json/src/Codec/CBOR/JSON.hs
Adds some benchmarks for `cbor-json` to show that replacing the hand rolled implementation of `decodeListN` is much slower than using `Vector`'s `replicateM`. Results using the included 8MB real world JSON document before the change:
```
> stack bench cborg-json:bench:bench --ba "-o before-vec.html -L 100 -I 0.1"
...
cborg-json-0.2.1.0: benchmarks
Running 1 benchmarks...         
Benchmark bench: RUNNING...     
benchmarking Decode/JSON        
time                 274.7 ms   (274.5 ms .. 274.8 ms, ci 0.100)
0.999 R²   (0.999 R² .. 0.999 R², ci 0.100)
mean                 276.8 ms   (276.7 ms .. 277.0 ms, ci 0.100)
std dev              5.796 ms   (5.855 ms .. 6.143 ms, ci 0.100)
benchmarking Decode/CBOR        
time                 512.0 ms   (511.5 ms .. 512.4 ms, ci 0.100)
0.999 R² …
```
> Use replicateM to significantly increase CBOR -> JSON value parsing speed

- cborg/cborg.cabal
- cborg/src/Codec/CBOR/ByteArray/Sliced.hs
- serialise/serialise.cabal
This patch bumps the `primitive` upper bound from `< 0.7` to `< 0.7.1`
> primitive-0.7.0.0 support

- cborg/cborg.cabal
- cborg/src/Codec/CBOR/Encoding.hs
- cborg/src/Codec/CBOR/FlatTerm.hs
- cborg/src/Codec/CBOR/Pretty.hs
- cborg/src/Codec/CBOR/Write.hs
- cborg/tests/Main.hs
- cborg/tests/Tests/PreEncoded.hs
This allows pre-encoded CBOR data to be included into an Encoding.
This is useful in cases where one has known-valid encoded CBOR data,  e.g. on disk, that you want to include into a larger CBOR data stream.  This makes it possible in such cases to avoid decoding and re-encoding.
Includes tests.
Supercedes #204
> Add an encodePreEncoded function

- cborg-json/ChangeLog.md
- cborg-json/src/Codec/CBOR/JSON.hs
NaNs and infinities are substituted with `null`s.
This handles all the problematic cases I had found in https://github.com/dhall-lang/dhall-haskell/issues/1350:
```
$ echo '[NaN, Infinity, -Infinity, 0.0, -0.0, 12.0]' | dhall encode > tmp
$ cabal run -- cbor-tool dump --json tmp
Up to date
[
4,
null,
null,
null,
null,
0,
0,
12
]
```
(The first `4` and `null` are Dhall's tags for a `List`.)
Partially addresses #145.
> cborg-json: Decode 16- and 32-bit floats too

- serialise/src/Codec/Serialise/Class.hs
- serialise/tests/Tests/Orphanage.hs
- serialise/tests/Tests/Serialise.hs
The demonstrator test fails:
```
type: SomeTypeRep
cbor roundtrip:                       FAIL
*** Failed! Exception: 'DeserialiseFailure 2 "Codec.CBOR.Class.decodeSomeTypeRep: unexpected tag\n"' (after 1 test):
[Either (Maybe Int) (Proxy (Kind *) ('Type * [Char]))]
Use --quickcheck-replay=754269 to reproduce.
flat roundtrip:                       FAIL
*** Failed! Falsified (after 1 test):
[Either (Maybe Int) (Proxy (Kind *) ('Type * [Char]))]
Use --quickcheck-replay=127810 to reproduce.
flat term is valid:                   OK
+++ OK, passed 100 tests.
```
> Fix a `SomeTypeRep` tagging issue

- cborg/src/Codec/CBOR/Decoding.hs
Is there reason why `Decoder` is a data instead of newtype? According to micro benchmark micro/decoding/cbor this change gives speedup of 2.5% (9.5ms -> 9.3ms) with large errors
That's not much but hey, it's free!
> Make Decoder a newtype

- cborg/src/Codec/CBOR/Read.hs
- hie.yaml
When looking into #236 I noticed that trivial decodings of integers were performed lazily. For instance, in `tryConsumeInt` we had,
```haskell
tryConsumeInt hdr !bs = case word8ToWord hdr of
...
0x38 -> DecodedToken 2 (-1 - word8ToInt  (eatTailWord8 bs))
```
which will produce a thunk to perform some trivial widening and a subtraction. This seems completely unnecessary. This improves runtime in the case of the "small" testcase in #236 on the order 1%. Note that the "word" cases were generally fine to begin with (since e.g. `word8ToWord` will be inlined and simply allocates a `W#` constructor) but I applied strictness in these cases as well for the sake of consistency.
Also adds an `hie.yaml` although I'm happy to drop this if we would prefer.
> Perform packing of small integers eagerly

- cborg/cborg.cabal
Builds fine and all tests pass here.
> Allow base64-bytestring 1.2

- cbor-tool/cbor-tool.cabal
- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- cborg/src/Codec/CBOR/Write.hs
- serialise/serialise.cabal
http://hackage.haskell.org/package/bytestring-0.11.0.0/changelog
Since cborg uses the internal PS constructor which is a bundled pattern
synonym in bytestring >= 0.11, we stick to bytestring < 0.11 for
GHC < 8.0 where bundled pattern synonyms aren't supported.
> Add support for bytestring 0.11

- cborg/src/Codec/CBOR/Read.hs
- cborg/src/Codec/CBOR/Write.hs
* Migrate to native `ghc-bignum` interfaces.
* Don't use deprecated `-funfolding-keeness-factor` flag
I have looked at the Core of both `Read` and `Write` and saw no major regressions. Moreover, the `instances` benchmark compiled when by 9.0.1 looks quite good, with all benchmarks being either within uncertainty or significantly better than 8.10.4. Many encoding benchmarks in particular tend to be a factor of 3-4 better. See https://gist.github.com/bgamari/b3aea8f06dc240107b7eabdb7aa87a54 for a full accounting.
> Finish GHC 9 support

- serialise/ChangeLog.md
- serialise/serialise.cabal
- serialise/src/Codec/Serialise/Class.hs
`strict` is a recently-revived library containing strict versions of some base types, which also includes strict versions of `these` - , @phadej and I have been maintaining it.
This PR contains the relevant `Serialise` instances for those types. We thought it was better to keep these instances here instead of inside `strict` itself, because `strict` is meant to be a light library with minimal dependencies. Recently `aeson` and `lens` have added instances there too, depending on `strict`.
> add instances for these, strict

- .github/workflows/haskell-ci.yml
- binary-serialise-cbor/binary-serialise-cbor.cabal
- cbor-tool/cbor-tool.cabal
- cborg-json/cborg-json.cabal
- cborg/cborg.cabal
- cborg/src/Codec/CBOR/Decoding.hs
- cborg/src/Codec/CBOR/FlatTerm.hs
- cborg/src/Codec/CBOR/Magic.hs
- cborg/src/Codec/CBOR/Read.hs
- serialise/serialise.cabal
- serialise/src/Codec/Serialise/Class.hs
- serialise/tests/Tests/Serialise.hs
This adapts all of the `cborg` packages to compile with GHC 9.2.
> Adapt for GHC 9.2.1

- cborg/cborg.cabal
- serialise/serialise.cabal
I made a corresponding revision https://hackage.haskell.org/package/cborg-0.2.6.0/revisions/
> Allow semigroups-0.20

- serialise/src/Codec/Serialise/Tutorial.hs
Went through the tutorial & found its writing confusing.
It is for `serialise` library, but `Serialise.Tutorial` advertised itself as `cborg` tutorial & talked mainly about `cborg` package, `serialise` package was never mentioned, etc. Also, there seemed to be some repetitiveness in the text
So decided to revise the tutorial a bit.
> Serialise.Tutorial: update

- cborg/ChangeLog.md
- cborg/src/Codec/CBOR/ByteArray/Internal.hs
- cborg/src/Codec/CBOR/ByteArray/Sliced.hs
Implementation of `SlicedByteArray` is totally wrong whenever offset is present. This was discovered when roundtrip property was implemented elsewhere.
> Fix SlicedByteArray

- cborg-json/cborg-json.cabal
- cborg-json/src/Codec/CBOR/JSON.hs
- cborg-json/tests/Main.hs
- serialise/serialise.cabal
I am implementing WebAuthn authentication.
Chrome browser returns part of data encoded in CBOR and uses 58/59 bytes (fixed byte string with length up to 255/65535 bytes) to encode key.
I think exposing such type as a hex string in JSON is best option.
Aeson.Array Number is much less efficient.
+ extra dependency on base16
> Adds support for ByteStrings in inside JSON

- cborg/src/Codec/CBOR/FlatTerm.hs
Now `tokenTypeOf` distinguishes between:
- Unsigned 64 bit integers `(0     <= n < 2^64)`: `TypeUInt64`
- Negative 64 bit integers `(-2^64 < n  < 0   )`: `TypeNInt64`
- Integers outside the ranges above             : `TypeInteger`
Fixes https://github.com/well-typed/cborg/issues/324
> Make `tokenTypeOf` more precise

- .github/workflows/macwin.yml
... especially mac is now aarch64, so it's good to test. It doesn't have cheap unaligned reads, AFAIK, at least cbor.h enables them for x86/64 archs only.
> Add simple mac and win CI
